name: Fetch planning permits
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt install libgbm1
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: fetch-planning-permits
      run: |-
        cd permits
        npm install puppeteer
        node fetch-planning-permits.js
    - run: mv permits/RecordList* permits/record-list.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Alameda Built Bot"
        git config user.email "dda+alameda+built@dara-abrams.com"
        git add '*.csv'
        timestamp=$(date -u)
        git commit -m "Latest version of planning permits" || exit 0
        git push
